on:
  schedule:
    - cron: '* * * 10 *'
  repository_dispatch:
    types: [check-link]
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - 'main'
      - 'master'
      - '*'

name: Broken Link Check
jobs:
  print-token:
    permissions: write-all
    name: print-token
    environment: dev
    runs-on: ubuntu-latest
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with:
          EXCLUDED_KEYWORDS: docs.github.com
        env: 
          GITHUB_TOKEN: ${{ github.token }}
